/**
 * Jira Export Utility (Copy-to-Clipboard MVP)
 *
 * Formats a report as Jira-compatible markdown for pasting into a new issue.
 * Jira uses its own wiki markup but also accepts markdown-like formatting
 * when pasted into the rich-text editor.
 */

import { extractDashboardData } from "@/lib/dashboard-data-parser";

function extractKeyPoints(text: string): string[] {
  if (!text) return [];
  const cleaned = text.replace(/<dashboard-data>[\s\S]*?<\/dashboard-data>/g, "");
  const lines = cleaned.split("\n").filter((l) => l.trim().length > 0);
  const keywords = ["recommend", "suggest", "should", "key", "important", "critical", "action"];
  const matched = lines.filter((l) =>
    keywords.some((kw) => l.toLowerCase().includes(kw))
  );
  return (matched.length > 0 ? matched : lines).slice(0, 8).map((l) =>
    l.replace(/^[#\-*>\d.]+\s*/, "").replace(/\*\*/g, "").trim()
  );
}

/**
 * Escape a value for safe inclusion inside a Jira wiki-markup table cell.
 * Prevents pipe-based table breakout and wiki macro injection.
 */
function sanitizeJiraCell(value: string): string {
  if (!value) return value;
  return value
    .replace(/\|/g, "\\|")      // escape pipe (table cell delimiter)
    .replace(/\{/g, "\\{")      // escape opening brace (Jira macros: {code}, {panel}, etc.)
    .replace(/\[/g, "\\[");     // escape bracket (Jira links: [text|url])
}

export function formatReportForJira(
  scenarioTitle: string,
  analysisResult: string,
  formData: Record<string, string>,
  timestamp: string,
): string {
  const date = new Date(timestamp).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const sections: string[] = [];

  // Title
  sections.push(`h2. [EXOS] ${scenarioTitle} — ${date}`);
  sections.push("");

  // Executive Summary
  const keyPoints = extractKeyPoints(analysisResult);
  if (keyPoints.length > 0) {
    sections.push("h3. Executive Summary");
    keyPoints.forEach((kp) => sections.push(`* ${kp}`));
    sections.push("");
  }

  // Analysis Inputs
  const inputs = Object.entries(formData);
  if (inputs.length > 0) {
    sections.push("h3. Analysis Inputs");
    sections.push("||Parameter||Value||");
    inputs.forEach(([key, value]) => {
      const label = key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
      sections.push(`|${sanitizeJiraCell(label)}|${sanitizeJiraCell(value)}|`);
    });
    sections.push("");
  }

  // Action Items (if action-checklist exists)
  const dashData = extractDashboardData(analysisResult);
  if (dashData?.actionChecklist?.actions?.length) {
    sections.push("h3. Action Items");
    dashData.actionChecklist.actions.forEach((a) => {
      const icon =
        a.status === "done" ? "(/) "
        : a.status === "in-progress" ? "(!) "
        : a.status === "blocked" ? "(x) "
        : "(-) ";
      const ownerTag = a.owner ? ` — _${a.owner}_` : "";
      sections.push(`* ${icon}*[${a.priority.toUpperCase()}]* ${a.action}${ownerTag}`);
    });
    sections.push("");
  }

  // Footer
  sections.push("----");
  sections.push(`_Generated by EXOS on ${date}_`);

  return sections.join("\n");
}
