/**
 * Jira Export Utility (Copy-to-Clipboard MVP)
 *
 * Formats a report as Jira-compatible markdown for pasting into a new issue.
 * Jira uses its own wiki markup but also accepts markdown-like formatting
 * when pasted into the rich-text editor.
 */

import { extractDashboardData, isStructuredOutput } from "@/lib/dashboard-data-parser";
import type { ExosOutput } from "@/lib/sentinel/types";

function extractKeyPoints(text: string): string[] {
  if (!text) return [];
  const cleaned = text.replace(/<dashboard-data>[\s\S]*?<\/dashboard-data>/g, "");
  const lines = cleaned.split("\n").filter((l) => l.trim().length > 0);
  const keywords = ["recommend", "suggest", "should", "key", "important", "critical", "action"];
  const matched = lines.filter((l) =>
    keywords.some((kw) => l.toLowerCase().includes(kw))
  );
  return (matched.length > 0 ? matched : lines).slice(0, 8).map((l) =>
    l.replace(/^[#\-*>\d.]+\s*/, "").replace(/\*\*/g, "").trim()
  );
}

/**
 * Escape a value for safe inclusion inside a Jira wiki-markup table cell.
 */
function sanitizeJiraCell(value: string): string {
  if (!value) return value;
  return value
    .replace(/\|/g, "\\|")
    .replace(/\{/g, "\\{")
    .replace(/\[/g, "\\[");
}

/**
 * Format a structured EXOS Output Schema v1.0 report for Jira.
 */
function formatStructuredForJira(parsed: ExosOutput): string {
  const sections: string[] = [];

  // Confidence header
  sections.push(`h2. [EXOS] ${parsed.scenario_name}`);
  sections.push(`[CONFIDENCE: ${parsed.confidence_level}]`);
  if (parsed.low_confidence_watermark) {
    sections.push("⚠ LOW CONFIDENCE — KEY DATA MISSING");
  }
  sections.push("");

  // Summary
  sections.push(parsed.summary);
  sections.push("");

  // Executive bullets
  if (parsed.executive_bullets?.length > 0) {
    sections.push("h3. Key Findings");
    parsed.executive_bullets.forEach(b => sections.push(`* ${sanitizeJiraCell(b)}`));
    sections.push("");
  }

  // Data gaps
  if (parsed.data_gaps?.length > 0) {
    sections.push("h3. Data Gaps");
    parsed.data_gaps.forEach(g => {
      sections.push(`* {color:red}[DATA GAP]{color} *${sanitizeJiraCell(g.field)}*: ${sanitizeJiraCell(g.impact)}`);
    });
    sections.push("");
  }

  // Recommendations (HIGH priority only as sub-tasks)
  const highRecs = parsed.recommendations?.filter(r => r.priority === 'HIGH') ?? [];
  if (highRecs.length > 0) {
    sections.push("h3. Priority Actions");
    highRecs.forEach(r => {
      const impact = r.financial_impact ? ` — ${sanitizeJiraCell(r.financial_impact)}` : '';
      sections.push(`* → ${sanitizeJiraCell(r.action)}${impact}`);
    });
    sections.push("");
  }

  // Footer — gdpr_flags never exported
  sections.push("----");
  sections.push(`_Generated by EXOS · Schema v${parsed.schema_version}_`);

  return sections.join("\n");
}

/**
 * @deprecated Legacy Jira formatter — use structured output path when available
 */
export function formatReportForJira(
  scenarioTitle: string,
  analysisResult: string,
  formData: Record<string, string>,
  timestamp: string,
): string {
  // Try structured EXOS Output Schema v1.0 first
  if (isStructuredOutput(analysisResult)) {
    try {
      const parsed = JSON.parse(analysisResult) as ExosOutput;
      return formatStructuredForJira(parsed);
    } catch { /* fall through to legacy */ }
  }

  const date = new Date(timestamp).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  const sections: string[] = [];

  sections.push(`h2. [EXOS] ${scenarioTitle} — ${date}`);
  sections.push("");

  const keyPoints = extractKeyPoints(analysisResult);
  if (keyPoints.length > 0) {
    sections.push("h3. Executive Summary");
    keyPoints.forEach((kp) => sections.push(`* ${kp}`));
    sections.push("");
  }

  const inputs = Object.entries(formData);
  if (inputs.length > 0) {
    sections.push("h3. Analysis Inputs");
    sections.push("||Parameter||Value||");
    inputs.forEach(([key, value]) => {
      const label = key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
      sections.push(`|${sanitizeJiraCell(label)}|${sanitizeJiraCell(value)}|`);
    });
    sections.push("");
  }

  const dashData = extractDashboardData(analysisResult);
  if (dashData?.actionChecklist?.actions?.length) {
    sections.push("h3. Action Items");
    dashData.actionChecklist.actions.forEach((a) => {
      const icon =
        a.status === "done" ? "(/) "
        : a.status === "in-progress" ? "(!) "
        : a.status === "blocked" ? "(x) "
        : "(-) ";
      const ownerTag = a.owner ? ` — _${a.owner}_` : "";
      sections.push(`* ${icon}*[${a.priority.toUpperCase()}]* ${a.action}${ownerTag}`);
    });
    sections.push("");
  }

  sections.push("----");
  sections.push(`_Generated by EXOS on ${date}_`);

  return sections.join("\n");
}
