import ScenarioLandingPage from '@/components/scenarios/ScenarioLandingPage';

export default function BlackSwan() {
  return (
    <ScenarioLandingPage
      metaTitle="Supply Chain Risk Simulation Software | EXOS"
      metaDescription="Simulate catastrophic supply chain disruptions before they happen. EXOS Black Swan Scenario Simulator builds proactive mitigation roadmaps for EU procurement and supply chain teams."
      canonicalPath="/scenarios/black-swan-simulation"
      category="Risk"
      h1="Supply Chain Risk Simulation Software"
      subtitle="Model the disruptions you hope will never happen — before they do. Build mitigation roadmaps while you still have time to act."
      heroMetric="2 months"
      heroMetricLabel="Average early warning lead time generated by EXOS risk monitoring"
      whatItDoesTitle="What the Black Swan Simulator Does"
      whatItDoesParagraph="Black Swan events — sudden supplier insolvency, geopolitical trade disruptions, regulatory bans, natural disasters affecting key sourcing regions — are by definition unpredictable in timing but predictable in category. EXOS Black Swan Simulator models the impact of these catastrophic scenarios on your specific supply chain: which categories are most exposed, what the financial and operational impact would be, and what mitigation steps are available at each stage of escalation. The output is a prioritised disruption response playbook, not a generic risk register."
      features={[
        { icon: "Zap", title: "Scenario Modelling", description: "Simulate supplier insolvency, geopolitical disruptions, regulatory bans, and logistics failures against your actual category portfolio." },
        { icon: "AlertOctagon", title: "Impact Quantification", description: "Financial and operational impact calculated per scenario — revenue at risk, production delay costs, and emergency sourcing premiums." },
        { icon: "Map", title: "Mitigation Roadmap", description: "Staged response playbook: immediate actions, 30-day stabilisation, and 90-day resilience build." },
        { icon: "Radio", title: "Real-Time Signal Grounding", description: "Scenarios grounded in live market intelligence — geopolitical alerts, supplier news, and regulatory changes via Perplexity Sonar." }
      ]}
      whoItIsFor={[
        { role: "VP Supply Chain", need: "Needs board-ready disruption scenarios and response playbooks before an annual risk review." },
        { role: "CPO", need: "Building supply chain resilience strategy and requires quantified exposure analysis per category." },
        { role: "Risk Manager", need: "Documenting catastrophic supply chain risks for insurance, compliance, or investor reporting purposes." },
        { role: "Operations Director", need: "Identifying single-source exposure and geographic concentration risks before they become operational crises." }
      ]}
      proof={{
        quote: "When our primary tungsten supplier faced EU regulatory action, EXOS had already flagged the risk two months prior. The contingency plans we had built using the Black Swan module kept our production lines running.",
        person: "Erik Lindqvist, VP Supply Chain",
        company: "NordSteel Industries AB",
        metric: "6-week production halt avoided"
      }}
      relatedScenarios={[
        { name: "Supplier Risk Assessment", path: "/scenarios/supplier-risk-assessment", description: "Multi-dimensional supplier risk scoring across financial, legal, cyber, and operational dimensions." },
        { name: "Disruption Management", path: "/features", description: "Emergency response planning for active supply chain disruptions with alternative sourcing strategies." },
        { name: "Supplier Dependency & Exit Planner", path: "/features", description: "Build diversification roadmaps to reduce concentration risk before a crisis forces your hand." }
      ]}
    />
  );
}
