ALTER TABLE public.procurement_categories
  ADD COLUMN IF NOT EXISTS aliases text[] NOT NULL DEFAULT '{}';

COMMENT ON COLUMN public.procurement_categories.aliases IS
  'Alternative names / synonyms (2-5) used by the chatbot to advise users how to search for this category in the catalogue.';

UPDATE public.procurement_categories SET aliases = CASE slug
  WHEN 'adhesives-sealants-coatings' THEN ARRAY['Glues','Bonding agents','Industrial sealants','Surface coatings','Paints']
  WHEN 'air-freight-express-logistics' THEN ARRAY['Air cargo','Express courier','Airfreight forwarding','Time-critical shipping']
  WHEN 'audit-tax-accounting-services' THEN ARRAY['Big 4 audit','External auditors','Tax advisory','Bookkeeping','Statutory audit']
  WHEN 'banking-financial-services' THEN ARRAY['Corporate banking','Treasury services','Trade finance','FX services']
  WHEN 'cables-wire-harnesses' THEN ARRAY['Wiring harnesses','Cable assemblies','Electrical cabling','Looms']
  WHEN 'calibration-testing-inspection-services' THEN ARRAY['TIC services','Quality testing','Metrology','Third-party inspection','NDT']
  WHEN 'capital-equipment-industrial-machinery' THEN ARRAY['CapEx machinery','Production equipment','Industrial machines','Plant equipment']
  WHEN 'castings-forgings-machined-parts' THEN ARRAY['Metal castings','Forged parts','Machined components','Foundry parts']
  WHEN 'catering-workplace-food-services' THEN ARRAY['Canteen services','Corporate catering','Workplace dining','Food service']
  WHEN 'chemicals-specialty' THEN ARRAY['Specialty chemicals','Performance chemicals','Fine chemicals','Industrial chemicals']
  WHEN 'clinical-research-organisation-cro-services' THEN ARRAY['CRO','Clinical trials outsourcing','Clinical research providers','Trial management']
  WHEN 'cloud-infrastructure-iaas-paas' THEN ARRAY['AWS / Azure / GCP','Cloud hosting','IaaS','PaaS','Public cloud']
  WHEN 'cold-chain-logistics' THEN ARRAY['Refrigerated transport','Temperature-controlled logistics','Frozen freight','Reefer logistics']
  WHEN 'construction-materials' THEN ARRAY['Building materials','Cement & aggregates','Civil works materials']
  WHEN 'contingent-workforce-temp-staffing' THEN ARRAY['Temp labour','Contractors','Agency workers','MSP staffing','Flexible workforce']
  WHEN 'contract-manufacturing' THEN ARRAY['CM / CMO','Outsourced manufacturing','OEM production','Toll manufacturing']
  WHEN 'corporate-travel' THEN ARRAY['Business travel','TMC services','Travel management','T&E']
  WHEN 'cosmetics-personal-care-ingredients' THEN ARRAY['Personal care actives','Cosmetic raw materials','Beauty ingredients']
  WHEN 'customs-brokerage-trade-compliance' THEN ARRAY['Customs clearance','Import/export brokerage','Trade compliance','Freight forwarding (customs)']
  WHEN 'cybersecurity-solutions' THEN ARRAY['InfoSec tools','SecOps','SIEM/EDR','Security software','SOC services']
  WHEN 'electronic-components' THEN ARRAY['Passives & actives','Resistors & capacitors','Discrete electronics','Distributor components']
  WHEN 'events-exhibitions-sponsorship' THEN ARRAY['Trade shows','Conference sponsorship','Event management','Exhibitions']
  WHEN 'facilities-management' THEN ARRAY['FM services','Hard & soft FM','Building maintenance','Cleaning & janitorial']
  WHEN 'fasteners-springs-fixings' THEN ARRAY['Bolts & screws','Nuts and washers','C-parts','Fixings']
  WHEN 'filters-filtration-systems' THEN ARRAY['Filtration media','Industrial filters','Air & liquid filters']
  WHEN 'fleet-management' THEN ARRAY['Vehicle fleet','Company cars','Fleet leasing','Car fleet operations']
  WHEN 'food-ingredients' THEN ARRAY['Food raw materials','F&B ingredients','Functional food ingredients','Commodity food inputs']
  WHEN 'hr-recruitment' THEN ARRAY['Permanent recruitment','Headhunting','Talent acquisition','RPO','Executive search']
  WHEN 'insurance-corporate' THEN ARRAY['Commercial insurance','Risk transfer','D&O / liability cover','Property & casualty']
  WHEN 'it-hardware' THEN ARRAY['Laptops & desktops','End-user devices','Servers','Computer hardware']
  WHEN 'it-software-saas' THEN ARRAY['SaaS subscriptions','Enterprise software','Cloud apps','Application licences']
  WHEN 'lab-supplies' THEN ARRAY['Laboratory consumables','Lab reagents','Lab consumables','Research supplies']
  WHEN 'last-mile-e-commerce-fulfilment' THEN ARRAY['Last-mile delivery','E-commerce fulfilment','3PL fulfilment','Home delivery']
  WHEN 'legal-services' THEN ARRAY['External counsel','Law firms','Outside legal','Legal advisory']
  WHEN 'logistics-road-freight' THEN ARRAY['Trucking','Road haulage','FTL/LTL','Road transport']
  WHEN 'logistics-sea-freight' THEN ARRAY['Ocean freight','Container shipping','Sea cargo','FCL/LCL']
  WHEN 'logistics-small-parcel' THEN ARRAY['Parcel delivery','Courier services','Small package shipping','Express parcels']
  WHEN 'managed-it-services-msp' THEN ARRAY['MSP','Outsourced IT','Managed services','IT support outsourcing']
  WHEN 'management-consulting-advisory' THEN ARRAY['Strategy consulting','Big 3 consulting','Management advisory','Business consultants']
  WHEN 'market-research-data-intelligence' THEN ARRAY['Market intelligence','Data subscriptions','Industry research','Insights providers']
  WHEN 'marketing-services' THEN ARRAY['Advertising agencies','Digital marketing','Media buying','Creative services']
  WHEN 'medical-devices-clinical-consumables' THEN ARRAY['Med devices','Clinical consumables','Hospital supplies','Surgical instruments']
  WHEN 'medical-software-health-it-systems' THEN ARRAY['Health IT','EHR/EMR systems','Clinical software','Healthcare IT']
  WHEN 'mro-maintenance-repair-operations' THEN ARRAY['MRO supplies','Indirect spare parts','Maintenance parts','Industrial supplies']
  WHEN 'nutraceuticals-supplement-ingredients' THEN ARRAY['Supplement ingredients','Vitamins & minerals','Botanical extracts','Functional ingredients']
  WHEN 'office-supplies' THEN ARRAY['Stationery','Office consumables','Print & paper','General office']
  WHEN 'packaging-primary' THEN ARRAY['Primary pack','Bottles & containers','Direct contact packaging','Product packaging']
  WHEN 'personal-protective-equipment-ppe' THEN ARRAY['PPE','Safety gear','Workwear','Protective clothing','Gloves & masks']
  WHEN 'pharmaceutical-ingredients-apis' THEN ARRAY['API','Active pharmaceutical ingredients','Drug substances','Pharma intermediates']
  WHEN 'plastics-resins' THEN ARRAY['Polymers','Plastic resins','Polyolefins','Engineering plastics']
  WHEN 'precision-machining-subcontract-engineering' THEN ARRAY['CNC machining','Subcontract engineering','Precision parts','Job shops']
  WHEN 'printed-circuit-boards-pcbs' THEN ARRAY['PCB','Printed boards','PCBA','Bare boards']
  WHEN 'printing-creative-production' THEN ARRAY['Print production','Commercial printing','Creative production','Print management']
  WHEN 'professional-services' THEN ARRAY['Advisory services','Consulting (general)','Specialist advisors','External experts']
  WHEN 'raw-materials-steel-metals' THEN ARRAY['Steel','Aluminium','Base metals','Ferrous & non-ferrous','Metal coil & sheet']
  WHEN 'real-estate-property-leasing' THEN ARRAY['Office leasing','Corporate real estate','Property rental','CRE']
  WHEN 'rubber-elastomers' THEN ARRAY['Rubber compounds','Elastomers','Synthetic rubber','Moulded rubber parts']
  WHEN 'scientific-laboratory-equipment-capital' THEN ARRAY['Lab instruments','Analytical equipment','Lab capex','Scientific instruments']
  WHEN 'secondary-packaging-labels-print' THEN ARRAY['Cartons & cases','Labels','Secondary pack','Corrugated packaging']
  WHEN 'security-services-physical' THEN ARRAY['Manned guarding','Physical security','Guard services','On-site security']
  WHEN 'semiconductors' THEN ARRAY['Chips','ICs','Microcontrollers','Silicon components']
  WHEN 'surface-treatment-plating-coating' THEN ARRAY['Plating','Anodising','Surface finishing','Industrial coating services']
  WHEN 'telecom-equipment' THEN ARRAY['Network equipment','Telecom hardware','Routers & switches','Comms gear']
  WHEN 'telecoms-connectivity-services' THEN ARRAY['Telecom services','Connectivity','MPLS / SD-WAN','Mobile & data plans','ISP services']
  WHEN 'textile-fabrics' THEN ARRAY['Fabrics','Woven & knitted textiles','Apparel materials','Technical textiles']
  WHEN 'tooling-dies-moulds' THEN ARRAY['Tooling','Injection moulds','Stamping dies','Press tools']
  WHEN 'training-education' THEN ARRAY['Corporate training','L&D','Learning & development','Upskilling programmes']
  WHEN 'utilities-energy' THEN ARRAY['Electricity & gas','Energy procurement','Power supply','Utilities']
  WHEN 'warehouse-services' THEN ARRAY['Warehousing','3PL storage','Distribution centres','Contract logistics']
  WHEN 'waste-management-recycling' THEN ARRAY['Waste services','Recycling','Skip & disposal','Circular waste']
  ELSE aliases
END;