
-- Table to store monitor reports generated by the system
CREATE TABLE public.monitor_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tracker_id uuid NOT NULL REFERENCES public.enterprise_trackers(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES public.organizations(id),
  report_content text NOT NULL,
  citations jsonb DEFAULT '[]'::jsonb,
  model_used text DEFAULT 'sonar-pro',
  processing_time_ms integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.monitor_reports ENABLE ROW LEVEL SECURITY;

-- RLS: users can see reports for their org trackers
CREATE POLICY "select_in_org" ON public.monitor_reports
  FOR SELECT TO authenticated
  USING (
    is_super_admin(auth.uid())
    OR organization_id = get_user_org_id(auth.uid())
  );

-- RLS: no direct insert from client (edge function uses service_role)
CREATE POLICY "no_direct_insert" ON public.monitor_reports
  FOR INSERT TO authenticated
  WITH CHECK (false);

-- Auto-set org trigger
CREATE TRIGGER set_monitor_reports_org
  BEFORE INSERT ON public.monitor_reports
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_set_organization_id();
